In [1]:
! git clone https://github.com/jeslago/epftoolbox.git

fatal: destination path 'epftoolbox' already exists and is not an empty directory.


In [2]:
% cd epftoolbox

! pwd

/content/epftoolbox
/content/epftoolbox


In [3]:
! pip install .

Processing /content/epftoolbox
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
  Created wheel for epftoolbox: filename=epftoolbox-1.0-py3-none-any.whl size=66419 sha256=7fbdbba358f64c7273530af5a58fdce65f129b0bb9f03ea0ba65a811d0b782a0
  Stored in directory: /tmp/pip-ephem-wheel-cache-u7930g1h/wheels/06/b5/e7/02ff8b49a8bcb96199cd1c61796efa62c3e0a1a6a30807e150
Successfully built epftoolbox
  Attempting uninstall: epftoolbox
    Found existing installation: epftoolbox 1.0
    Uninstalling epftoolbox-1.0:
      Successfully uninstalled epftoolbox-1.0


In [4]:
import pandas as pd
from epftoolbox.data import read_data

**read_data()**

If `dataset` is either ``"PJM"``, ``"NP"``, ``"BE"``, ``"FR"``, or ``"DE"``,
    the function checks whether ``dataset.csv`` exists in ``path``. If it doesn't exist,
    it downloads the data from an online database and saves it under the ``path`` directory. ``"PJM"``

In [5]:
# '.' means current directoory
df_train, df_test = read_data(path='.', dataset='PJM', begin_test_date='01-01-2016', end_test_date='01-02-2016')

print(df_train.shape,df_test.shape)

df_train.head()
# df_train.tail()

Test datasets: 2016-01-01 00:00:00 - 2016-02-01 23:00:00
(26280, 3) (768, 3)


Price  Exogenous 1  Exogenous 2
Date                                                    
2013-01-01 00:00:00  25.464211      85049.0      11509.0
2013-01-01 01:00:00  23.554578      82128.0      10942.0
2013-01-01 02:00:00  22.122277      80729.0      10639.0
2013-01-01 03:00:00  21.592066      80248.0      10476.0
2013-01-01 04:00:00  21.546501      80850.0      10445.0

In [6]:
# df_test.head()
df_test.tail()

Price  Exogenous 1  Exogenous 2
Date                                                    
2016-02-01 19:00:00  28.056729      99400.0      12680.0
2016-02-01 20:00:00  26.916456      97553.0      12495.0
2016-02-01 21:00:00  24.041505      93983.0      12267.0
2016-02-01 22:00:00  22.044896      88535.0      11747.0
2016-02-01 23:00:00  20.593339      82900.0      10974.0

In [7]:
# for val in df_test.values:
  # print(val)

**Data Scaling**

In [8]:
from epftoolbox.data import DataScaler

# Training Data
Xtrain = df_train.values

scaler = DataScaler('Norm')
Xtrain_scaled = scaler.fit_transform(Xtrain)
Xtrain_inverse = scaler.inverse_transform(Xtrain_scaled)

print(Xtrain.shape,Xtrain_scaled.shape,Xtrain_inverse.shape)

print("\n Sample Xtrain \n\n",Xtrain[:3:])
print("\n Sample Xtrain_scaled \n\n",Xtrain_scaled[:3:])
print("\n Sample Xtrain_inverse\n\n",Xtrain_inverse[:3:])

(26280, 3) (26280, 3) (26280, 3)

 Sample Xtrain 

 [[2.5464211e+01 8.5049000e+04 1.1509000e+04]
 [2.3554578e+01 8.2128000e+04 1.0942000e+04]
 [2.2122277e+01 8.0729000e+04 1.0639000e+04]]

 Sample Xtrain_scaled 

 [[0.03833877 0.2736787  0.28415155]
 [0.03608228 0.24425597 0.24633138]
 [0.03438982 0.23016409 0.2261206 ]]

 Sample Xtrain_inverse

 [[2.5464211e+01 8.5049000e+04 1.1509000e+04]
 [2.3554578e+01 8.2128000e+04 1.0942000e+04]
 [2.2122277e+01 8.0729000e+04 1.0639000e+04]]


In [9]:
# Test Data
Xtest  = df_test.values
Xtest_scaled  = scaler.transform(Xtest)
Xtest_inverse = scaler.inverse_transform(Xtest_scaled)

print(Xtest.shape,Xtest_scaled.shape,Xtest_inverse.shape)

print("\n Sample Xtest \n\n",Xtest[:3:])
print("\n Ssample Xtest_scaled \n\n",Xtest_scaled[:3:])
print("\n Sample Xtest_inverse \n\n",Xtest_inverse[:3:])

(768, 3) (768, 3) (768, 3)

 Sample Xtest 

 [[2.0341321e+01 7.6840000e+04 1.0406000e+04]
 [1.9462741e+01 7.4819000e+04 1.0075000e+04]
 [1.7172706e+01 7.3182000e+04 9.7950000e+03]]

 Ssample Xtest_scaled 

 [[0.03228538 0.19099086 0.21057898]
 [0.03124721 0.17063368 0.18850053]
 [0.02854122 0.15414446 0.16982391]]

 Sample Xtest_inverse 

 [[2.0341321e+01 7.6840000e+04 1.0406000e+04]
 [1.9462741e+01 7.4819000e+04 1.0075000e+04]
 [1.7172706e+01 7.3182000e+04 9.7950000e+03]]


**Forecasting Models**

In [10]:
from epftoolbox.evaluation import MAPE

In [11]:
path = '/content/epftoolbox/forecasts/Forecasts_NP_DNN_LEAR_ensembles.csv'

forecast = pd.read_csv(path,index_col = 0)

print(forecast.shape)
forecast.head()

(17472, 11)


Real price      DNN 1      DNN 2      DNN 3      DNN 4  \
2016-12-27 00:00:00       24.08  24.530144  24.838255  25.126823  25.108997   
2016-12-27 01:00:00       22.52  23.115845  23.608419  23.390991  23.871862   
2016-12-27 02:00:00       20.13  22.563509  22.815233  22.686951  23.168064   
2016-12-27 03:00:00       19.86  22.047380  22.582897  22.360287  23.127621   
2016-12-27 04:00:00       20.09  23.055725  23.158974  22.911869  23.744692   

                     DNN Ensemble  LEAR 56  LEAR 84  LEAR 1092  LEAR 1456  \
2016-12-27 00:00:00     24.901055  25.1290  24.9381    24.3565    24.8109   
2016-12-27 01:00:00     23.496779  24.2083  24.4645    22.0323    22.6447   
2016-12-27 02:00:00     22.808439  23.9289  23.8766    20.9948    20.8664   
2016-12-27 03:00:00     22.529546  23.4943  24.2399    20.6269    19.4584   
2016-12-27 04:00:00     23.217815  23.5104  24.5551    20.7978    20.7202   

                     LEAR Ensemble  
2016-12-27 00:00:00      24.808625  
2016-12-27 01:00:00      23.337450  
2016-12-27 02:00:00      22.416675  
2016-12-27 03:00:00      21.954875  
2016-12-27 04:00:00      22.395875

In [12]:
forecast.columns

Index(['Real price', 'DNN 1', 'DNN 2', 'DNN 3', 'DNN 4', 'DNN Ensemble',
       'LEAR 56', 'LEAR 84', 'LEAR 1092', 'LEAR 1456', 'LEAR Ensemble'],
      dtype='object')

In [13]:
# Transforming indices to datetime format

forecast.index = pd.to_datetime(forecast.index)
print(forecast.index[:3])

DatetimeIndex(['2016-12-27 00:00:00', '2016-12-27 01:00:00',
               '2016-12-27 02:00:00'],
              dtype='datetime64[ns]', freq=None)


In [14]:
_, df_test = read_data(path='.', dataset = 'NP', begin_test_date = forecast.index[0],end_test_date = forecast.index[-1])

# we are only interested in test data as the forecast is done in test data itself.
print(df_test.shape)
print(df_test.head(3))
print(df_test.tail(2))

Test datasets: 2016-12-27 00:00:00 - 2018-12-24 23:00:00
(17472, 3)
                     Price  Exogenous 1  Exogenous 2
Date                                                
2016-12-27 00:00:00  24.08      42653.0       2124.0
2016-12-27 01:00:00  22.52      41868.0       1905.0
2016-12-27 02:00:00  20.13      41534.0       2053.0
                     Price  Exogenous 1  Exogenous 2
Date                                                
2018-12-24 22:00:00  49.02      50928.0       3119.0
2018-12-24 23:00:00  48.10      49889.0       3306.0


In [15]:
# Extracting forecast of DNN ensemble and display
fc_DNN_ensemble = forecast.loc[:, ['DNN Ensemble']]

fc_DNN_ensemble[:3]

DNN Ensemble
2016-12-27 00:00:00     24.901055
2016-12-27 01:00:00     23.496779
2016-12-27 02:00:00     22.808439

In [16]:
# Extracting real price and display
real_price = df_test.loc[:, ['Price']]

real_price[:25]

Price
Date                      
2016-12-27 00:00:00  24.08
2016-12-27 01:00:00  22.52
2016-12-27 02:00:00  20.13
2016-12-27 03:00:00  19.86
2016-12-27 04:00:00  20.09
2016-12-27 05:00:00  23.93
2016-12-27 06:00:00  26.23
2016-12-27 07:00:00  27.76
2016-12-27 08:00:00  28.06
2016-12-27 09:00:00  27.98
2016-12-27 10:00:00  28.05
2016-12-27 11:00:00  28.27
2016-12-27 12:00:00  28.33
2016-12-27 13:00:00  28.43
2016-12-27 14:00:00  28.57
2016-12-27 15:00:00  28.83
2016-12-27 16:00:00  29.51
2016-12-27 17:00:00  29.72
2016-12-27 18:00:00  29.65
2016-12-27 19:00:00  29.39
2016-12-27 20:00:00  29.14
2016-12-27 21:00:00  28.37
2016-12-27 22:00:00  27.24
2016-12-27 23:00:00  25.73
2016-12-28 00:00:00  26.45

In [17]:
print(fc_DNN_ensemble.shape)
fc_DNN_ensemble.values.reshape(-1, 24).shape

# making data according to the 24 our time span thus if our dataaset size is n then 
# number of cols will be 24 and number of rows will be -1 that is number of rows = n//24
# print(fc_DNN_ensemble.shape[0]//24)

(17472, 1)


(728, 24)

In [18]:
fc_DNN_ensemble_2D = pd.DataFrame(fc_DNN_ensemble.values.reshape(-1, 24), index = fc_DNN_ensemble.index[::24], 
                                  columns=['h' + str(hour) for hour in range(24)])

fc_DNN_ensemble_2D.head()

h0         h1         h2         h3         h4         h5  \
2016-12-27  24.901055  23.496779  22.808439  22.529546  23.217815  24.983548   
2016-12-28  25.164850  24.544741  24.135444  24.194813  24.824976  26.329212   
2016-12-29  28.330177  27.697056  27.186900  27.012188  27.179504  27.685595   
2016-12-30  27.948486  27.374095  27.076586  26.985007  27.261047  28.093092   
2016-12-31  26.366282  25.459522  24.848794  24.535461  24.638456  25.235196   

                   h6         h7         h8         h9  ...        h14  \
2016-12-27  27.243211  28.459138  28.849062  28.753552  ...  29.040955   
2016-12-28  28.606312  30.422346  31.215793  31.162506  ...  31.901268   
2016-12-29  28.501660  29.342222  29.592036  29.592638  ...  29.000770   
2016-12-30  29.392045  30.291307  30.557754  30.508921  ...  29.743407   
2016-12-31  26.144166  26.835132  27.438794  27.707542  ...  27.640527   

                  h15        h16        h17        h18        h19        h20  \
2016-12-27  29.509694  29.928786  30.470445  29.981456  29.487300  29.032756   
2016-12-28  32.694648  33.704986  34.494267  33.343340  31.208918  30.013822   
2016-12-29  29.192838  29.649752  29.813154  29.590336  29.101284  28.583012   
2016-12-30  29.963455  30.157590  30.428876  30.178187  29.801478  29.454844   
2016-12-31  27.842996  28.237323  28.609344  28.459385  28.029734  27.614226   

                  h21        h22        h23  
2016-12-27  28.640429  27.806076  26.643023  
2016-12-28  29.153526  28.375926  27.324923  
2016-12-29  28.204550  27.970621  27.199672  
2016-12-30  29.083482  28.470059  27.713009  
2016-12-31  27.410532  26.989756  26.243367  

[5 rows x 24 columns]

In [22]:
real_price_2D = pd.DataFrame(real_price.values.reshape(-1, 24), index=real_price.index[::24], 
                             columns=['h' + str(hour) for hour in range(24)] )

real_price_2D.head()

h0     h1     h2     h3     h4     h5     h6     h7     h8  \
Date                                                                        
2016-12-27  24.08  22.52  20.13  19.86  20.09  23.93  26.23  27.76  28.06   
2016-12-28  26.45  26.26  26.24  26.43  27.26  28.72  29.81  30.64  31.86   
2016-12-29  29.26  28.72  28.29  28.32  28.95  29.88  30.66  30.96  31.27   
2016-12-30  28.18  27.03  26.47  26.47  27.14  28.33  29.53  30.06  30.28   
2016-12-31  25.11  23.65  22.99  22.13  22.57  23.47  25.03  25.78  26.82   

               h9  ...    h14    h15    h16    h17    h18    h19    h20  \
Date               ...                                                    
2016-12-27  27.98  ...  28.57  28.83  29.51  29.72  29.65  29.39  29.14   
2016-12-28  31.98  ...  32.88  33.24  33.88  33.81  32.89  31.90  31.24   
2016-12-29  31.05  ...  31.08  31.27  31.54  31.47  30.99  30.58  30.28   
2016-12-30  30.25  ...  30.12  30.29  30.51  30.39  30.27  30.20  29.56   
2016-12-31  27.89  ...  28.52  29.11  29.50  29.57  29.24  28.38  27.98   

              h21    h22    h23  
Date                             
2016-12-27  28.37  27.24  25.73  
2016-12-28  30.65  30.02  29.37  
2016-12-29  30.01  29.44  28.76  
2016-12-30  28.96  27.77  25.95  
2016-12-31  27.52  26.80  26.71  

[5 rows x 24 columns]

* According to the paper, the MAPE of the DNN ensemble for the NP market is 5.38%.

In [23]:
# Evaluating MAPE when real price and forecasts are both dataframes

MAPE(p_pred = fc_DNN_ensemble, p_real = real_price) * 100

5.38352491508943

In [24]:
# Evaluating MAPE when real price and forecasts are both numpy arrays

MAPE(p_pred = fc_DNN_ensemble.values, p_real = real_price.values) * 100

5.38352491508943

In [25]:
# Pandas Series

MAPE(p_pred=fc_DNN_ensemble.loc[:, 'DNN Ensemble'], p_real=real_price.loc[:, 'Price']) * 100

5.38352491508943

In [26]:
# Numpy arrays

MAPE(p_pred=fc_DNN_ensemble.values.squeeze(), p_real=real_price.values.squeeze()) * 100

5.38352491508943

In [27]:
# Evaluating MAPE when input values are of shape (ndays, n_prices/day) instead 
# of shape (nprices, 1)
# Dataframes

MAPE(p_pred=fc_DNN_ensemble_2D, p_real=real_price_2D) * 100

5.38352491508943